---
title: "Blatt 4"
author: "Data Science 2"
date: "Wintersemester 2023/2024"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

*Hinweis:* Halten Sie Ihre Lösungen (insbesondere R-Code) hier und auch bei allen künftigen Aufgaben kurz, verständlich und übersichtlich. Für mathematische Notation bietet sich die \LaTeX-Syntax an, die beispielsweise im Anhang B des eLehrbuchs zu Data Science 1 (bookdown.org/marktrede/DS1Deskription) knapp zusammengefasst ist. In Data Science I haben Sie gelernt, wie Sie eine HTML-Datei durch Ihre Markdown-Datei erstellen können. Wir bitten Sie darum, diese in eine PDF-Datei zu konvertieren.

In manchen Aufgaben werden Sie dazu aufgefordert, formale Aussagen zu zeigen. Wir bitten Sie darum, diese Rechnungen entweder in der Markdown-Datei mit der \LaTeX-Syntax zu schreiben oder diese Aussagen analog auf Papier (oder digital) anzufertigen und Sie in die PDF-Datei einzufügen. Am Ende sollten Sie genau eine PDF-Datei im Learnweb abgeben.

# Aufgabe 1:

Sei $X \sim Po(100)$. Sei $f(x):=10x^2 +3$ für $x \in \mathbb{R}$. Der Träger der Zufallsvariable $f(X)$ ist also $$
T_{f(X)}:= \left\lbrace 10\cdot z^{2} + 3 : z \in \mathbb{N}_0 \right\rbrace.
$$

a)  Approximieren Sie den Erwartungswert sowie die Varianz der Zufallsvariablen $f(X)$ mittels Monte-Carlo-Simulation, indem Sie $10\,000$ unabhängige Realisationen der Zufallsvariable $X$ generieren.

b)  Ermitteln Sie den Erwarungswert von $f(X)$ analytisch. Wie groß ist die absolute Abweichung zum approximierten Erwartungswert? Wie groß ist diese relativ zum analytischen Erwartungswert?

c)  Stellen Sie die Verteilungsfunktion von $f(X)$ mittels Monte-Carlo-Simulation anhand von $10\,000$ Realisationen der Zufallsvariable $X$ grafisch dar.

d)  Zeigen Sie, dass $$
    P\left(f(X)=n\right)=e^{-\lambda}\frac{\lambda^{\sqrt{(n-3)/10}}}{\left(\sqrt{\frac{n-3}{10}}\right)!}~~~\text{ für } n\in T_{f(X)}~~\text{ und } \lambda:=100.
    $$ *Hinweis*: Für $X \geq 0$ und $n \geq 0$ gilt $P(X^2 = n ) = P(X = \sqrt{n})$.

<!-- e)  Berechnen Sie den Unterschied zur simulierten Wahrscheinlichkeitsfunktion (an den Stellen, die in der Simulation vorkommen). Zur Berechnung des Unterschieds nutzen Sie bitte die mittlere absolute Abweichung $\frac{1}{n}\sum_{k=1}^{n}|g(x_k)-h(x_k)|$ für zwei Wahrscheinlichkeitsfunktionen $g$ und $h$. -->


# Aufgabe 2

Die Verteilung des zu versteuernden (Jahres-)Einkommens in Deutschland soll durch eine lognormalverteilte Zufallsvariable $V$ modelliert werden. In R gibt es für die Lognormalverteilung die Funktionen $\texttt{dlnorm}$ (Dichte), $\texttt{plnorm}$ (Verteilungsfunktion), $\texttt{qlnorm}$ (Quantile) und $\texttt{rlnorm}$ (Zufallszahlen). Die Parameter der Lognormalverteilung heißen in R $\texttt{meanlog}$ und $\texttt{sdlog}$. Um das zu versteuernde Einkommen zu modellieren, werden die beiden Parameter auf $\texttt{meanlog}=10.2$ und $\texttt{sdlog}=1.6$ gesetzt.

Legen Sie für die weitere Bearbeitung der Aufgabe § 32a Absatz 1 des Einkommensteuergesetzes (EStG) unter Vernachlässigung der §§ 32b, 32d, 34, 34a, 34b und 34c EStG zu Grunde. Sie finden § 32a Absatz 1 EStG unter: \url{https://www.gesetze-im-internet.de/estg/__32a.html}.

a)  Approximieren Sie den Erwartungswert $E(V)$ und die Standardabweichung $\sqrt{Var(V)}$ des zu versteuernden Einkommens durch eine Monte-Carlo-Simulation.

b)  Approximieren Sie die Dichte des \emph{logarithmierten} zu versteuernden Einkommens $\ln(V)$ durch eine Monte-Carlo-Simulation und stellen Sie sie als Histogramm dar. Welche Verteilung erkennen Sie näherungsweise? Berechnen Sie auch hier Erwartungswert und Standardabweichung. Was fällt hinsichtlich der Parameter der oben genutzten Lognormalverteilung auf?

c)  Approximieren Sie die Verteilungsfunktion der tariflichen Einkommensteuer $s(V)$, wobei $s(\cdot)$ die im EStG genannte Steuerfunktion ist. Stellen Sie die Verteilungsfunktion anschließend grafisch dar.

d)  Stellen Sie die geschätzte Verteilungsfunktion des Nettoeinkommens (definiert als zu versteuerndes Einkommen minus tarifliche Einkommensteuer) grafisch dar.

*Hinweise:*

-   Nutzen Sie für alle vier Aufgabenteile eine Monte-Carlo-Simulation mit $10\,000$ Realisationen.

-   Die Nutzung einer Schleife könnte hilfreich sein.

-   Die R-Funktion zum Abrunden lautet $\texttt{floor}$.

-   Berücksichtigen Sie in den grafischen Darstellungen lediglich Einkommen zwischen $0$ und $300\,000$ Euro. Dies erreichen Sie z. B. mittels des Parameters `xlim = c(0,3*10^5)` in den Funktionen $\texttt{hist}$ und $\texttt{plot}$.\
    Beispiel:\
    `rexp(10^4, rate=1/10^5)`

    `hist(x,breaks=100, probability=TRUE, xlim=c(0,3*10^5))`


# Aufgabe 3

Seien $X_1,X_2,\ldots,X_{20}$ unabhängige Wiederholungen von $X\sim t_4$ (d.h. eine t-Verteilung mit 4 Freiheitsgraden). Es gilt $E(X)=0$. Die Varianz von $X$ beträgt $Var(X)=2$. Mit $Y_n$ bezeichnen wir die Partialsummen $$
Y_n=\sum_{i=1}^n X_i
$$ für $n=1,\ldots,20$.

a)  Leiten Sie für $n,m\in\{1,2,\ldots,20\}$ mit $m\le n$ die Kovarianz $Cov(Y_m,Y_n)$ analytisch her.

b)  Führen Sie eine Monte-Carlo-Simulation durch, um das 0.1-Quantil von $Y_{20}$ zu bestimmen.

c)  Approximieren Sie mit Hilfe einer Monte-Carlo-Simulation die Wahrscheinlichkeit, dass sowohl $Y_{10}$ als auch $Y_{20}$ strikt positiv sind.

d)  Wie hoch ist der bedingte Erwartungswert von $Y_{20}$, wenn $Y_{10}$ strikt positiv ist? Ermitteln Sie den Wert mit Hilfe einer Monte-Carlo-Simulation.

*Hinweise*:

-   Erinnern Sie sich für Teilaufgabe a) an die Verträglichkeit der Kovarianz mit Summen oder schauen Sie sich das Lösungsvideo zu Aufgabe 1 von Hausaufgabenblatt 3 an.

-   Die Realisationen von $Y_{10}$ und $Y_{20}$ sollten *nicht* auf unterschiedlichen Stichproben beruhen, da so die in a) nachgewiesene Abhängigkeit nicht mehr gegeben wäre.

-   Um den bedingten Erwartungswert in d) zu berechnen, können Sie die Stichprobe zunächst entsprechend der Bedingung einschränken und dann den Erwartungswert ermitteln.


# Aufgabe 4: Pi raten

Eine Möglichkeit die Kreiszahl $\pi$ zu schätzen, besteht darin sehr viele (hier $n$) Kugeln unabhängig voneinander rechteckverteilt in einen Sandkasten mit quadratischer Grundfläche fallen zu lassen. Stellen Sie sich dafür vor, dass Sie ein Koordinatensystem über diesen Sandkasten legen, sodass der Mittelpunkt auf der Koordinate $(0,0)$ liegt, dabei bedeutet die Rechteckverteilung in diesem Sandkasten, dass der Aufprallpunkt der Kugeln durch den Zufallsvektor $(X,Y)$ beschrieben werden kann, wobei $X$ und $Y$ unabhängig und rechteckverteilt sind. Gehen Sie außerdem davon aus, dass die Seitenlänge dieses Sandkastens 1 beträgt. Sie ziehen nun einen Kreis um den Mittelpunkt des Sandkastens mit Radius $\frac{1}{2}$. Wir notieren die Koordinaten $(x,y)$ der Aufprallpunkte der Kugeln und ermitteln, wie groß der Anteil der in den Innenkreis des Quadrats gefallenen Kugeln an den insgesamt fallen gelassenen Kugeln ist. Eine Kugel ist in den Innenkreis des Quadrats gefallen, falls für ihre Koordinaten $x^2 + y^2\le(1/2)^2$ gilt. Die Idee hinter dem Vorgehen besteht darin auszunutzen, dass $P(K) = \pi(1/2)^2$ mit $K$="Der Aufprallpunkt liegt im Kreis" gilt. Außerdem nutzen wir aus, dass nach dem Gesetz der großen Zahl der Anteil nährungsweise der Wahrscheinlichkeit $P(K)$ entspricht, wenn sehr viele Kugeln geworfen werden.

a)  Beschreiben Sie verbal einen Algorithmus, mit dem nach dem oben beschriebenen Verfahren eine Approximation von $\pi$ ermittelt werden kann.

b)  Approximieren Sie $\pi$, indem Sie den Algorithmus in R implementieren und ausführen. Erläutern Sie Ihr Vorgehen und geben Sie Zwischenergebnisse aus. Setzen Sie die Anzahl der Kugeln auf $n=10^5$.





# Aufgabe 5:

Seien $Y \sim U[-5,5]$, $Z \sim U[20,40]$ und $M \sim B(1,p)$ drei unabhängige Zufallsvariablen. $X$ sei eine weitere Zufallsvariable. Sie nimmt den Wert von $Y$ an, falls $M=1$ und den Wert von $Z$, falls $M=0$. Sei $X_1,\dots,X_n$ eine einfache Stichprobe aus $X$. Nehmen Sie an, dass $p=0.5$.

Hinweise: Nutzen Sie für alle Aufgabenteile Monte-Carlo-Simulationen mit möglichst $10\,000$ Realisationen. Setzen Sie in den zu erstellenden Histogrammen den Parameter `breaks=100`. In Aufgabenteil d) sind $\bar X_n$ und $S$ als Zufallsvariablen zu interpretieren, während $\mu$ der vorab geschätzte Wert aus Aufgabenteil a) ist.

a)  Wie hoch ist der Erwartungswert von $X$? Wie hoch wäre der Erwartungswert von $X$, wenn $p=0.9$ wäre?

b)  Approximieren Sie die Dichte der Zufallsvariable $X$, indem Sie das zugehörige Histogramm erstellen.

c)  Bestimmen Sie die Dichte der Zufallsvariable $X_1+\ldots+X_n$ für $n=3$ und $n=10$, indem Sie die zugehörigen Histogramme erstellen.

d)  Zeigen Sie grafisch, dass die Dichte der Zufallsvariable $$
    \sqrt{n}\frac{\bar X_n-\mu}{S}
    $$ für $n=100$ gut durch eine Standardnormalverteilung approximiert werden kann. Die Stichprobenstandardabweichung $$
    S = \sqrt{\frac{1}{n-1}\sum_{i=1}^n (X_i-\bar X_n)^2}
    $$ kann in R mit \texttt{sd} berechnet werden.

