# Zufallsvektoren {#zufallsvektoren}

Zufallsvariablen sind Funktionen aus dem Ergebnisraum in die Menge der
reellen Zahlen. Es ist natürlich möglich, nicht nur eine solche Funktion 
zu betrachten, sondern mehrere gleichzeitig. Man erhält dann mehrere
Zufallsvariablen, die jedoch alle vom gleichen zugrundeliegenden 
Zufallsvorgang abhängen und auf dem gleichen Ergebnisraum $\Omega$
basieren. Ordnet man diese Zufallsvariablen in Form eines
Vektors an, dann spricht man von einem **Zufallsvektor** 
(engl. random vector). Man sagt
auch, dass die Zufallsvariablen eine **gemeinsame Verteilung** 
(engl. joint distribution) haben.

Gemeinsame Verteilungen sind erheblich interessanter und vielseitiger
als eindimensionale Zufallsvariablen, weil sie auch Zusammenhänge
und Abhängigkeiten zwischen den Variablen beschreiben können.

::: callout-tip
- Zwei Würfel werden geworfen. Die Zufallsvariable $X$ sei die
kleinere Augenzahl, die Zufallsvariable $Y$ die größere Augenzahl.
Die beiden Zufallsvariablen $X$ und $Y$ basieren auf dem gleichen
Ergebnisraum. Sie haben eine gemeinsame Verteilung. Das lässt
sich etwa so veranschaulichen:
$$
\begin{array}{lclcl}
\mathbb{R}& X & \Omega & Y & \mathbb{R}\\\hline
1 & \longleftarrow & 11 & \longrightarrow & 1\\
1 & \longleftarrow & 12 & \longrightarrow & 2\\
1 & \longleftarrow & 13 & \longrightarrow & 3\\
1 & \longleftarrow & 14 & \longrightarrow & 4\\
1 & \longleftarrow & 15 & \longrightarrow & 5\\
1 & \longleftarrow & 16 & \longrightarrow & 6\\
1 & \longleftarrow & 21 & \longrightarrow & 2\\
2 & \longleftarrow & 22 & \longrightarrow & 2\\
2 & \longleftarrow & 23 & \longrightarrow & 3\\
\vdots && \vdots&&\vdots\\
5 & \longleftarrow & 65 & \longrightarrow & 6\\
6 & \longleftarrow & 66 & \longrightarrow & 6
\end{array}
$$

- Wir betrachten die Tagesrenditen von zwei Aktien an einem zukünftigen Tag. 
Sei $X$ die Tagesrendite der Volkswagenaktie und $Y$ die Tagesrendite von
BASF. Dann haben $X$ und $Y$ eine gemeinsame Verteilung.
:::

Im folgenden gehen wir Schritt für Schritt fast genauso vor wie bei den 
univariaten Zufallsvariablen in Kapitel XXX.

## Verteilungsfunktion

Alle wichtigen Eigenschaften der Verteilung einer univariaten 
Zufallsvariable werden durch ihre Verteilungsfunktion beschrieben. 
Wie lässt sich die Idee einer Verteilungsfunktion auf 
Zufallsvektoren übertragen? 

::: callout-note
Sei $\Omega$ eine Ergebnismenge, seien $X:\Omega \longrightarrow \mathbb{R}$ 
und $Y:\Omega\longrightarrow \mathbb{R}$ zwei Zufallsvariablen. Dann ist
\[ F_{XY}(x,y) =P(X\leq x,Y\leq y) \]
die **gemeinsame Verteilungsfunktion** (engl. joint cumulative
distribution function) von $X$ und $Y$.
:::

Wenn aus dem Kontext eindeutig hervorgeht, um welchen Zufallsvektor
bzw. um welche Zufallsvariablen es sich handelt, kann der Subindex entfallen.
Die gemeinsame Verteilungsfunktion lässt sich leicht auf mehr als zwei
Zufallsvariablen verallgemeinern. Da die Notation dann etwas unübersichtlicher
wird, beschränken wir uns auf den Fall von zwei Zufallsvariablen. Alle
wichtigen Konzepte lassen sich auch gut in diesem Fall verstehen.

Eigenschaften der gemeinsamen Verteilungsfunktion:

- $F_{XY}(x,y)=P(X\leq x,Y\leq y)$ ist monoton steigend 
(aber nicht unbedingt streng monoton steigend) in $x$ und $y$.

- Es gilt $\lim_{x\to -\infty}F_{XY}(x,y)$ und $\lim_{y\to -\infty}F_{XY}(x,y)=0$.

- Es gilt $\lim_{z\to \infty}F_{XY}(z,z) =1$.

## Gemeinsam diskrete Zufallsvariablen

Im univariaten Fall haben wir uns auf zwei Klassen von Zufallsvariablen
beschränkt, nämlich diskrete und stetige Zufallsvariablen. Das 
lässt sich leicht auf den mehrdimensionalen Fall verallgemeinern. 

::: callout-note
Zwei Zufallsvariablen $X$ und $Y$ heißen **gemeinsam diskret**
(jointly discrete),  wenn es endlich viele oder 
abzählbar unendlich viele Werte 
$x_1,x_2,\ldots$ und $y_1,y_2,\ldots $ gibt, so dass 
$$
\sum_{j}\sum_{k}p_{jk}=1
$$
mit $p_{jk}=P(X=x_j,Y=y_k)$.
:::

Gemeinsam diskrete Zufallsvariablen haben eine 
**gemeinsame Wahrscheinlichkeitsfunktion**
(engl. joint probability function), nämlich
$$
f_{XY}(x,y) =\left\{ 
\begin{array}{ll}
p_{jk} & \quad \text{für }x=x_{j}\text{ und }y=y_{k} \\ 
0 & \quad \text{sonst.}
\end{array}\right.
$$
Wenn die Zahl der unterschiedlichen möglichen Werte, die $X$ und $Y$
annehmen können, nicht allzu groß ist, dann kann man die 
gemeinsamen Wahrscheinlichkeiten übersichtlich in Form einer
Wahrscheinlichkeitstabelle darstellen:
$$
\begin{array}{c|ccc}
X\backslash Y & y_{1} & \ldots & y_{K} \\ \hline
x_{1} & p_{11} & \ldots  & p_{1K} \\ 
\vdots& \vdots &  & \vdots  \\ 
x_{J} & p_{J1} & \ldots  & p_{JK}
\end{array}
$$

::: callout-tip
Zwei Würfel werden geworfen. Die gemeinsame Wahrscheinlichkeitsfunktion 
der beiden Zufallsvariablen $X$: "kleinere Augenzahl" und 
$Y$: "größere Augenzahl" sieht als Wahrscheinlichkeitstabelle so aus:
$$
\begin{array}{c|cccccc}
X\backslash Y & 1 & 2 & 3 & 4 & 5 & 6 \\ \hline
1 & \frac{1}{36} & \frac{2}{36} & \frac{2}{36} & \frac{2}{36} & \frac{2}{36} & \frac{2}{36} \\
2 & 0            & \frac{1}{36} & \frac{2}{36} & \frac{2}{36} & \frac{2}{36} & \frac{2}{36} \\
3 & 0            & 0            & \frac{1}{36} & \frac{2}{36} & \frac{2}{36} & \frac{2}{36} \\
4 & 0            & 0            & 0            & \frac{1}{36} & \frac{2}{36} & \frac{2}{36} \\
5 & 0            & 0            & 0            & 0            & \frac{1}{36} & \frac{2}{36} \\
6 & 0            & 0            & 0            & 0            & 0            & \frac{1}{36}
\end{array}
$$
Der Wert der gemeinsamen Verteilungsfunktion an der Stelle
$(x,y)=(5.3, 2)$ gibt die Wahrscheinlichkeit an, dass $X\le 5$ ist
und gleichzeitig $Y\le 2$. Diese Wahrscheinlichkeit ergibt sich,
indem man alle Wahrscheinlichkeiten aus der Tabelle addiert,
die in den ersten beiden Spalten ($Y\le 2$) und in den
ersten fünf Zeilen ($X\le 5.3$) stehen. Man erhält
$$
F_{XY}(5.3,2)=\frac{1}{36}+\frac{2}{36}+\frac{1}{36}=\frac{4}{36}=\frac{1}{9}.
$$
:::

## Gemeinsam stetige Zufallsvariablen

::: callout-note
Die Zufallsvariablen $X$ und $Y$ heißen **gemeinsam stetig**
(engl. jointly continuous), falls es eine Funktion $f_{XY} $ gibt mit 
$$
F_{XY}(x,y)=\int_{-\infty }^{y}\int_{-\infty }^{x}f_{XY}(u,v)dudv.
$$
Die Funktion $f_{XY}$ heißt **gemeinsame Dichte** oder Dichtefunktion
(engl. joint density function) von $X$ und $Y$.
:::

## Randverteilungen

## Unabhängigkeit

## Bedingte Verteilungen

## Kovarianz

## Linearkombinationen
