project:
  type: book

book:
  title: "Data Science 2: Statistische Inferenz"
  author: "Mark Trede"
  date: "Juni 2023"
  chapters:
    - index.qmd
    - 01-zufall.qmd
    - 02-wahrscheinlichkeit.qmd
    - 03-zufallsvariablen.qmd
    - 04-zufallsvektoren.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
  pdf:
    documentclass: scrreprt

editor: source

toc-title-document: "Inhalt"

toc-title-website: "In diesem Kapitel"

callout-icon: false

callout-tip-title: "Beispiele"

callout-note-title: "Definition"
