project:
  type: book

book:
  title: "Data Science 2"
  subtitle: "Statistische Inferenz"
  author: "Mark Trede"
  date: "2023-10-18"
  chapters:
    - index.qmd
    - 01-zufall.qmd
    - 02-wahrscheinlichkeit.qmd
    - 03-zufallsvariablen.qmd
    - 04-verteilungen.qmd
    - 05-zufallsvektoren.qmd
    - 06-kovarianz.qmd
    - 07-grenzwerte.qmd
    - 08-stichproben.qmd
    - 09-punktschaetzung.qmd
    - 10-intervallschaetzung.qmd
    - 11-hypothesentests.qmd
    - 12-erwartungswerttests.qmd
    - 13-weiteretests.qmd
    - 14-bootstrap.qmd
  appendices:
    - 15-programmieren.qmd
    - 16-mengen.qmd
    - 17-literatur.qmd

format:
  html:
    theme: sandstone
    css: styles.css
  pdf: 
    toc: true
    number-sections: true
    colorlinks: true
    fontsize: "10pt"
    fig-width: 5
    fig-height: 3.5
    fig-cap-location: top
editor: source

callout-icon: false
callout-tip-title: "Beispiel"
callout-note-title: "Definition"

language:
  toc-title-document: "Inhaltsverzeichnis"
  toc-title-website: "Auf dieser Seite"

  section-title-abstract: "Zusammenfassung"
  section-title-appendices: "Anhang"
  section-title-footnotes: "Fußnoten"
  section-title-references: "Literatur"
  section-title-reuse: "Wiederverwendung"
  section-title-copyright: "Urheberrechte"
  section-title-citation: "Zitat"

  title-block-author-single: "Autor"
  title-block-affiliation-single: "Zugehörigkeit"
  title-block-affiliation-plural: "Zugehörigkeiten"
  title-block-published: "Veröffentlicht am"
  title-block-modified: "Geändert"
  title-block-keywords: "Schlüsselwörter"

  callout-warning-title: "Warnung"
  callout-important-title: "Wichtig"
  callout-caution-title: "Vorsicht"

  code-summary: "Code"
  code-line: "Zeile"
  code-lines: "Zeilen"

  code-tools-menu-caption: "Code"
  code-tools-show-all-code: "Gesamten Code zeigen"
  code-tools-hide-all-code: "Gesamten Code verbergen"
  code-tools-view-source: "Quellcode anzeigen"
  code-tools-source-code: "Quellcode"

  copy-button-tooltip: "In die Zwischenablage kopieren"
  copy-button-tooltip-success: "Kopiert"

  repo-action-links-edit: "Seite editieren"
  repo-action-links-source: "Quellcode anzeigen"
  repo-action-links-issue: "Problem melden"

  back-to-top: "Zurück nach oben"

  search-no-results-text: "Keine Treffer"
  search-matching-documents-text: "Treffer"
  search-copy-link-title: "Link in die Suche kopieren"
  search-hide-matches-text: "Zusätzliche Treffer verbergen"
  search-more-match-text: "weitere Treffer in diesem Dokument"
  search-more-matches-text: "weitere Treffer in diesem Dokument"
  search-clear-button-title: "Zurücksetzen"
  search-detached-cancel-button-title: "Abbrechen"
  search-submit-button-title: "Abschicken"
  search-label: "Suchen"

  toggle-section: "Abschnitt umschalten"
  toggle-sidebar: "Seitenleiste umschalten"
  toggle-dark-mode: "Dunkelmodus umschalten"
  toggle-reader-mode: "Lesemodus umschalten"
  toggle-navigation: "Navigation umschalten"

  crossref-fig-title: "Abbildung"
  crossref-tbl-title: "Tabelle"
  crossref-def-title: "Definition"
  crossref-exm-title: "Beispiel"
  crossref-exr-title: "Übungsaufgabe"
  crossref-ch-prefix: "Kapitel"
  crossref-apx-prefix: "Anhang"
  crossref-sec-prefix: "Kapitel"
  crossref-eq-prefix: "Gleichung"
