project:
  type: book

book:
  title: "Data Science 2"
  subtitle: "Statistische Inferenz"
  author: "Mark Trede"
  date: "Juli 2023"
  chapters:
    - index.qmd
    - 01-zufall.qmd
    - 02-wahrscheinlichkeit.qmd
    - 03-zufallsvariablen.qmd
    - 04-verteilungen.qmd
    - 05-zufallsvektoren.qmd
<<<<<<< HEAD
    - 06-kovarianz.qmd
    - 07-grenzwerte.qmd
    - 08-stichproben.qmd
    - 09-punktschaetzung.qmd
    - 10-intervallschaetzung.qmd
    - 11-hypothesentests.qmd
  appendices:
    - 12-programmieren.qmd
    - 13-literatur.qmd
=======
    - 06-grenzwerte.qmd
    - 07-stichproben.qmd
    - 08-punktschaetzung.qmd
    - 09-intervallschaetzung.qmd
    - 10-hypothesentests.qmd
  appendices:
    - 11-programmieren.qmd
    - 12-literatur.qmd
>>>>>>> main

format:
  html:
    theme: sandstone
    css: styles.css

editor: source

callout-icon: false
callout-tip-title: "Beispiel"
callout-note-title: "Definition"

toc-title-document: "Inhalt"
toc-title-website: "In diesem Kapitel"
section-title-appendices: "Anhänge"
title-block-author-single: "Autor"
<<<<<<< HEAD

crossref-ch-prefix: "Kapitel"
crossref-apx-prefix: "Anhang"
crossref-sec-prefix: "Abschnitt"
=======

crossref-ch-prefix: "Kapitel"
crossref-apx-prefix: "Anhang"
crossref-sec-prefix: "Abschnitt"

callout-icon: false
callout-tip-title: "Beispiel"
callout-note-title: "Definition"
>>>>>>> main
